# Generated by Django 3.1.6 on 2021-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(default='', max_length=10)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
