# Generated by Django 3.1.6 on 2021-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210218_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='fomo',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
